#!/bin/zsh

[[ -f .clang-format ]] || clang-format -style=google -dump-config > .clang-format
find src/cli/include src/cli/src tests -regex ".*\.\(c\|h\|cpp\|hpp\)" -exec clang-format -i -style=file {} +
